name: Build Glimpse

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  discussions: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: windows
          - os: macos-latest
            platform: mac
          - os: ubuntu-latest
            platform: linux

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi
      shell: bash

    - name: Build app
      run: npm run build

    - name: Build for Windows
      if: matrix.platform == 'windows'
      run: |
        if [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
          npm run package:win -- --publish always
        else
          npm run package:win -- --publish never
        fi
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Generate latest.yml for Windows
      if: matrix.platform == 'windows' && startsWith(github.ref, 'refs/tags/')
      run: |
        VERSION=$(echo "${{ github.ref }}" | sed 's/refs\/tags\/v//')
        node scripts/generate-latest-yml.js "dist/Glimpse-Setup-${VERSION}.exe" "${VERSION}"
      shell: bash

    - name: Build for macOS
      if: matrix.platform == 'mac'
      run: |
        if [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
          npm run package:mac -- --publish always
        else
          npm run package:mac -- --publish never
        fi
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # For signed builds, add these secrets:
        # CSC_LINK: ${{ secrets.MAC_CERTS }}
        # CSC_KEY_PASSWORD: ${{ secrets.MAC_CERTS_PASSWORD }}
        
    - name: Generate latest-mac.yml for macOS
      if: matrix.platform == 'mac' && startsWith(github.ref, 'refs/tags/')
      run: |
        VERSION=$(echo "${{ github.ref }}" | sed 's/refs\/tags\/v//')
        # macOS用のlatest.yml生成（必要に応じて実装）
      shell: bash

    - name: Build for Linux
      if: matrix.platform == 'linux'
      run: |
        if [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
          npm run package:linux -- --publish always
        else
          npm run package:linux -- --publish never
        fi
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Generate latest-linux.yml for Linux
      if: matrix.platform == 'linux' && startsWith(github.ref, 'refs/tags/')
      run: |
        VERSION=$(echo "${{ github.ref }}" | sed 's/refs\/tags\/v//')
        # Linux用のlatest.yml生成（必要に応じて実装）
      shell: bash

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.platform }}-build
        path: dist/*.*
        if-no-files-found: error

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*.*
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}